#!/usr/bin/env bash

#if [ ! -z "$WWWUSER" ]; then
#    usermod -u $WWWUSER mac
#fi
#
## get supervisor to work
#if [ $# -gt 0 ]; then
#    exec gosu $WWWUSER "$@"
#else
#    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#fi

 /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
